### ISSUE TITLE
New fields

### ISSUE THREAD

**Issue by duvrai** [Eucharistie/streaming-links#1]
### Proposed Fields Update
```yaml
---
channel: Name of channel
community: Name of community
priests: [Priest name,Other priest]
locations:
- city: Some City
  country: BE
  diocese: Mechelen-Brussel
  dioceseRegion: Vlaams Brabant      # from kerknet
  location:
    lat: 0.00
    lon: 0.00
avatar:                              # avatar: not implemented yet,
  id: AbCdEfGhIjKlMnO789             #   will replace fbid, 
  type: facebookProfilePicture.      #   but with support for other avatars
streams:                             # 
- id: AbCdEfGhIjKlMnO789             # streams: not implemented yet, this 
  type: youtubeChanneID.             #   will replace youtubeChannelID.
timetable:
- time: 09:30
  days: [sun]
  excludingDates: [2020-12-31]
  kind: sundayMass
  language: nl
  location: 0                        # from locations field above, starting at 0
- title: Feest van de onschuldige kinderen # title is optional, 
  time: 10:00                        # we will find the feast in our liturgical calendar
  dates: [2020-12-28]
  language: nl
  kind: feast
facebook: https://www.facebook.com/someoneOnFacebook
youtube: https://www.youtube.com/someChannel
homepage: https://example.com

# deprecated fields
youtubeChannelID: AbCdEfGhIjKlMnO789
fbid: 1234567890
title: Some Title                    #this falls back to the filename when omitted, so we replace it with "channel"
---
description in markdown
```

**Comment by duvrai** [comment]
This schema is changing all the time which is a bad sign and also dangerous.
Another [live](https://github.com/Eucharistie/streaming-links/blob/master/docs/_kanalen/ktotv.md) example that I'll just paste here: 
```YAML
---
channel: KTO tv
community:
priests: [Paus Franciscus, andere priesters]
locations:
- city: Rome
  diocese: Rome
  country: IT
- city: Paris
  diocese: Paris
  country: FR
  community: Saint-Germain l'Auxerrois
- city: Lourdes
  diocese: Tarbes et Lourdes
  country: FR
timetable:
- time: 07:00
  days: [mon,tue,wed,thu,fri,sat]
  kind: weekMass
  language: fr
  location: 0
  priests: [0]
- time: 07:00
  days: [sun]
  kind: sundayMass
  language: fr
  location: 0
  priests: [0]
- days: [sun]
  time: 10:00
  kind: sundayMass
  language: fr
  location: 2
- time: 10:00
  days: [mon,tue,wed,thu,fri,sat]
  kind: weekMass
  language: fr
  location: 2
- time: 18:30
  days: [sun]
  kind: sundayMass
  language: fr
  location: 1
- time: 18:15
  days: [mon,tue,wed,thu,fri,sat]
  kind: weekMass
  language: fr
  location: 1
facebook: https://www.facebook.com/kto.television/
fbid: 143654702340655
youtube: https://www.youtube.com/user/KTOTV
homepage: http://ktotv.com/
youtubeChannelID: UCg0L6cPMNLv1gjsyzYqMG7g
---
KTO tv: Franstalige commentaar
```
When the schema settles I'll write the doc in the [wiki](https://github.com/Eucharistie/streaming-links/wiki).
