### ISSUE TITLE
Safari in-page search doesn't always work

### ISSUE THREAD

**Issue by duvrai** [Eucharistie/streaming-links#46]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/6885698/78026355-cd314d80-735b-11ea-8261-11c7b730445e.png">
Part of the problem may be:

```scss
.capitalize-first-letter {
  display: inline-block;
  &::first-letter {
    text-transform: uppercase;
  }
}
```
```HTML
<strong>
  <a href="/kanalen/ktotv.html" class="capitalize-first-letter">
    KTO tv
  </a>
</strong>
<p class="text-small text-gray-light">KTO tv: Franstalige commentaar
</p>
```
but that shouldn't affect the paragraph beneath ...

#16 might also help users.
